### ISSUE TITLE
Feature request: different color pin for different day of the week

### ISSUE THREAD

**Issue by Zamboniman** [kevin-vaghasiya/calendar-events-in-maps#1]
Hi, came across this tool thanks to Google, and I'm wondering if it is possible to select a date range for a week (Monday to Friday) and to have the pins show a different color for each day of the week.

I'm using this to route technicians for on-site jobs and am hoping for a quick and easy way to see at a glance where a given technician is each day of the week so as new jobs come in I can book the job for a technician that is already close by in the same area on a given day.

**Comment by kevin-vaghasiya** [comment]
@Zamboniman please share the colors for the markers.

**Comment by Zamboniman** [comment]
It doesn't matter at all what color is for what day of the week. A legend in the corner showing what color is for what day would be useful for this. Or, instead of different colors, perhaps a more visually useful way to do this would be to have each day of the week represented by an stylized letter icon, so events on Monday would be a stylized 'M', and the rest would follow as T, W, R, F, S, U. Thanks!

**Comment by kevin-vaghasiya** [comment]
@Zamboniman added that feature.
update the script and deploy new version.
![Screenshot 2023-08-05 at 12 35 59 PM](https://github.com/kevin-vaghasiya/calendar-events-in-maps/assets/58857285/0ea31eec-5151-418c-ab86-51d924f3850a)

**Comment by Zamboniman** [comment]
Thanks very much!!
